# Generated by Django 3.1.1 on 2021-11-19 13:34

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('votingapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='votingapp.poll'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 19, 13, 34, 30, 980774, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='poll',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 19, 13, 34, 30, 980810, tzinfo=utc)),
        ),
    ]
