# Generated by Django 3.1.1 on 2021-11-19 13:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('votingapp', '0002_auto_20211119_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 19, 13, 54, 38, 383980, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='poll',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 19, 13, 54, 38, 384014, tzinfo=utc)),
        ),
    ]
