# Generated by Django 3.1.1 on 2021-11-19 22:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('votingapp', '0004_auto_20211119_1827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='text',
        ),
        migrations.AlterField(
            model_name='poll',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 19, 22, 32, 6, 385703, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='poll',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 19, 22, 32, 6, 385736, tzinfo=utc)),
        ),
    ]
